// frontend/src/routes/create-goal/+page.svelte
<script>
    import { onMount } from 'svelte';
    let name = '';
    let description = '';
    let isSubmitting = false;
    let errorMessage = '';

    async function createGoal() {
        isSubmitting = true;
        errorMessage = '';

        try {
            const response = await fetch('https://localhost:5295/api/goal', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    name,
                    description,
                }),
            });

            if (response.ok) {
                // Handle successful goal creation, e.g., redirect or display success message
                alert('Goal created successfully!');
                name = '';
                description = '';
            } else {
                const errorData = await response.json();
                errorMessage = errorData.message || 'Failed to create goal.';
            }
        } catch (error) {
            console.error('Error:', error);
            errorMessage = 'An unexpected error occurred.';
        } finally {
            isSubmitting = false;
        }
    }
</script>

<style>
    .container {
        max-width: 600px;
        margin: auto;
        padding: 1rem;
    }

    .form-group {
        margin-bottom: 1rem;
    }

    .form-group label {
        display: block;
        margin-bottom: 0.5rem;
    }

    .form-group input,
    .form-group textarea {
        width: 100%;
        padding: 0.5rem;
        border: 1px solid #ddd;
        border-radius: 4px;
    }

    .form-group button {
        background-color: #4CAF50;
        color: white;
        padding: 0.5rem 1rem;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    .form-group button:disabled {
        background-color: #aaa;
        cursor: not-allowed;
    }
</style>

<div class="container">
    <h1 class="text-2xl font-bold mb-4">Create a New Goal</h1>
    {#if errorMessage}
        <div class="mb-4 text-red-500">{errorMessage}</div>
    {/if}
    <div class="form-group">
        <label for="name">Goal Name</label>
        <input id="name" type="text" bind:value={name} placeholder="Enter goal name" required />
    </div>
    <div class="form-group">
        <label for="description">Description</label>
        <textarea id="description" rows="4" bind:value={description} placeholder="Enter goal description" required></textarea>
    </div>
    <div class="form-group">
        <button on:click={createGoal} disabled={isSubmitting}>
            {#if isSubmitting}Creating...{/if}
            {#if !isSubmitting}Create Goal{/if}
        </button>
    </div>
</div>

// frontend/src/components/CreateGoal.jsx
import React, { useState } from 'react';
import axios from 'axios';

const API_URL = import.meta.env.VITE_API_URL;

const CreateGoal = () => {
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setSuccess(false);

    try {
      const response = await axios.post(`${API_URL}/api/Goal`, {
        name,
        description
      });

      if (response.status === 200) {
        setSuccess(true);
        setName('');
        setDescription('');
      }
    } catch (err) {
      setError('Failed to create goal. Please try again.');
    }
  };

  return (
    <div className="max-w-md mx-auto bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
      <h2 className="text-2xl font-bold text-gray-900 mb-4">Create New Goal</h2>
      {error && <p className="text-red-500 mb-4">{error}</p>}
      {success && <p className="text-green-500 mb-4">Goal created successfully!</p>}
      <form onSubmit={handleSubmit}>
        <div className="mb-4">
          <label htmlFor="name" className="block text-gray-700 text-sm font-bold mb-2">Name:</label>
          <input
            type="text"
            id="name"
            value={name}
            onChange={(e) => setName(e.target.value)}
            required
            maxLength={30}
            className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          />
        </div>
        <div className="mb-6">
          <label htmlFor="description" className="block text-gray-700 text-sm font-bold mb-2">Description:</label>
          <textarea
            id="description"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            maxLength={90}
            className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline h-24"
          />
        </div>
        <button 
          type="submit" 
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
        >
          Create Goal
        </button>
      </form>
    </div>
  );
};

export default CreateGoal;
